version: '3.8'

services:
  phpcli:
    build: docker/phpcli/
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - ./var/data:/app/var/data
      - miskas_composer:/root/.composer/

  db:
    image: mariadb:10.5.8
    restart: always
    volumes:
      - miskas_db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}

  redis:
    image: redis:6.0.10
    command: redis-server --appendonly yes
    volumes:
      - miskas_redis:/data

volumes:
  miskas_db:
  miskas_composer:
  miskas_redis:
