version: '3.8'

services:
  phpcli:
    build: docker/phpcli/
    depends_on:
      - db
    volumes:
      - .:/app
      - ./var/data:/app/var/data
  db:
    image: mariadb:10.5.8
    restart: always
    volumes:
      - miskas_db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}


volumes:
  miskas_db:
